### ISSUE TITLE
Reduce default plugins/packages

### ISSUE THREAD

**Issue by oxyc** [generoi/bedrock#246]

**Comment by bokorir** [comment]
Should I check a few latest projects and decide based on that? Or how should we decide which are the useful ones as default?

**Comment by oxyc** [comment]
True :D personal opinion would be https://gist.github.com/oxyc/db2fd900df8df25b13dd8b7d43597cc9/revisions

Thoughts?

Not having dropin installer might be confusing for people setting up redis first time though, pretty rare and usually done by senior
Not having composer-patches likewise but it's pretty rare you patch things
Stream i do enable whenever a client starts setting up a site so we know if we can blame them :D but leaning towards clean?
post-type-archive-mapping needs further filters to work properly can add it back later together with them if needed.
generoi/genero-conf would need this file moved into the repo https://github.com/generoi/genero-conf/blob/master/wp/wp-cli-pre-ssh.php
