### ISSUE TITLE
Add a stricter PHP, JS lint

### ISSUE THREAD

**Issue by oxyc** [generoi/bedrock#247]
Prettier would be nice so we can skip the whole "review code style" thing and focus on other things during reviews.

**Comment by bokorir** [comment]
@oxyc what standards do you think of for PHP? Should we use prettier with default config?

**Comment by oxyc** [comment]
Maybe we can discuss this in this weeks dev meeting?

Since prettier needs to run with JS I feel like it's a no go?

That leaves:
- Use it with your favorite code editor -> people will forget/not follow and that causes more havoc.

Maybe https://github.com/PHP-CS-Fixer/PHP-CS-Fixer works well enough even without prettier if we set up the roots code conventions?

**Comment by oxyc** [comment]
phpstan/rector?

**Comment by oxyc** [comment]
Fixed
