### ISSUE TITLE
Fix for PHP 8.1

### ISSUE THREAD

**Issue by oxyc** [generoi/bedrock#248]

**Comment by bokorir** [comment]
@oxyc you sent me when updated to PHP 8.0: 

`did a quick test to PHP 8.1 but all plugins and their siblings threw deprecation notices so... meh i dont want that in local development`

do you want me to proceed with this anyways?

**Comment by oxyc** [comment]
I would look into which plugins/core and see if there are upstream tasks where they are being worked on. Maybe we can contirbute patches too

**Comment by oxyc** [comment]
Seems to work without notices on PHP 8.2 now. We can update the default to 8.2 in a separate commit.
